### ISSUE TITLE
easy_install hookbox   doesn't pull in csp

### ISSUE THREAD

**Issue by loxs** [play-co/hookbox#22]
Of course, it works if csp is installed

**Comment by mcarter** [comment]
We recently moved from the "csp" module to the "csp_eventlet" module... 

What error did you get that caused you to file this bug?

**Comment by loxs** [comment]
just after easy_install-ing hookbox, if I try to run it, I get this:

(testvirt)loxs@antares ~/code $ hookbox 
Traceback (most recent call last):
  File "/home/loxs/code/testvirt/bin/hookbox", line 8, in <module>
    load_entry_point('hookbox==0.2.6', 'console_scripts', 'hookbox')()
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 318, in load_entry_point
    def has_metadata(name):
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 2221, in load_entry_point
    _normalize_cached(filename), os.path.basename(filename), metadata,
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['**name**'])
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/hookbox-0.2.6-py2.6.egg/hookbox/start.py", line 2, in <module>
    from server import HookboxServer
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/hookbox-0.2.6-py2.6.egg/hookbox/server.py", line 21, in <module>
    from admin.admin import HookboxAdminApp
  File "/home/loxs/code/testvirt/lib/python2.6/site-packages/hookbox-0.2.6-py2.6.egg/hookbox/admin/admin.py", line 4, in <module>
    import csp.eventlet as csp
ImportError: No module named csp.eventlet
(testvirt)loxs@antares ~/code $

**Comment by loxs** [comment]
if I easy_install csp, then hookbox just runs normally.

**Comment by mcarter** [comment]
the csp module is no longer needed. (switch to csp_eventlet)
