### ISSUE TITLE
if run with --debug, hokbox try to find a module that isn't installed

### ISSUE THREAD

**Issue by loxs** [play-co/hookbox#27]
$ ./hookboxStart.sh 
Listening to hookbox on http://0.0.0.0:8001
Traceback (most recent call last):
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/hubs/hub.py", line 249, in fire_timers
    timer()
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/hubs/timer.py", line 62, in **call**
    cb(_args, *_kw)
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/greenthread.py", line 195, in main
    result = function(_args, *_kwargs)
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/hookbox-0.2.6-py2.6.egg/hookbox/start.py", line 37, in debugloop
    from pyjsiocompile.compile import main as pyjsiocompile
ImportError: No module named pyjsiocompile.compile

**Comment by mcarter** [comment]
should be added in hookbox 0.3.2
