### ISSUE TITLE
hookbox is unable to relay messages with unicode characters

### ISSUE THREAD

**Issue by loxs** [play-co/hookbox#30]
I managed to write a simple chat application.
If I try writing in Bulgarian, Hookbox fails with the following error in the console:

Traceback (most recent call last):
  File "/home/Programming/pylons/virtualenv-0.9.7/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/wsgi.py", line 306, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python2.6/site-packages/paste/urlmap.py", line 202, in **call**
    return app(environ, start_response)
  File "build/bdist.linux-x86_64/egg/csp_eventlet/**init**.py", line 77, in **call**
    x = handler(session, environ, start_response)
  File "build/bdist.linux-x86_64/egg/csp_eventlet/**init**.py", line 100, in render_send
    session.read(environ['csp.form'].get('d', ''))
  File "build/bdist.linux-x86_64/egg/csp_eventlet/**init**.py", line 228, in read
    data = str(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-54: ordinal not in range(128)

**Comment by loxs** [comment]
It seems like the admin knows about this issue, because it byte encodes unicode strings before sending them to the channel.

**Comment by loxs** [comment]
The issue is very easy to fix. It's infact a csp_eventlet issue, but I don't know how to move it here

In csp_eventlet/**init**.py  just substitute
data = str(data)   with data=unicode(data)
