### ISSUE TITLE
Sometimes hookbox fails to autosubscribe users to channels.

### ISSUE THREAD

**Issue by loxs** [play-co/hookbox#36]
This happens when I return something like:
return  [True, {'name': session.get('user').get('userid'), 'auto_subscribe': ['global', session.get('user').get('partnerid')]}]
in my /hookbox/connect controller.
This only happens sometimes:

Traceback (most recent call last):
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/hubs/poll.py", line 99, in wait
    listener(fileno)
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/hubs/hub.py", line 21, in **call**
    return self.cb(_args, *_kw)
  File "/home/loxs/itembase/virtualenv/lib/python2.6/site-packages/eventlet-0.9.7-py2.6.egg/eventlet/greenthread.py", line 195, in main
    result = function(_args, *_kwargs)
  File "/home/loxs/Software/hookbox/hookbox/server.py", line 216, in maybe_auto_subscribe
    channel.subscribe(user, needs_auth=False)
  File "/home/loxs/Software/hookbox/hookbox/channel.py", line 222, in subscribe
    conn.send_frame('SUBSCRIBE', frame)
AttributeError: 'NoneType' object has no attribute 'send_frame'
Removing descriptor: 5

**Comment by mcarter** [comment]
Can you paste the relevant webhook and console logs from the admin panel in here and turn off rest formatting somehow, (perhaps an external paste tool?)

**Comment by loxs** [comment]
http://friendpaste.com/3TsZS2p5x0iyuos6koN4pz
http://friendpaste.com/5dcq5m3s8nkEU7RVcgs15w

**Comment by loxs** [comment]
Yes, seems like http://github.com/mcarter/hookbox/commit/ebd5ea8c517955f94c73d035b33be6cdf49f3abe
fixed the issue

**Comment by mcarter** [comment]
closing this issue
