### ISSUE TITLE
non ascii payloads generate exceptions

### ISSUE THREAD

**Issue by ergo** [play-co/hookbox#40]
when i try to send 'grzegżółka' i get following exception:

<pre>

WARNING:RTJPConnection:Unexpected error: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ergo/python/lib/python2.5/site-packages/hookbox-0.2.10-py2.5.egg/hookbox/protocol.py", line 64, in _run
    f(fid, fargs)
  File "/home/ergo/python/lib/python2.5/site-packages/hookbox-0.2.10-py2.5.egg/hookbox/protocol.py", line 117, in frame_PUBLISH
     channel.publish(self.user, fargs.get('payload', 'null'), conn=self)
  File "/home/ergo/python/lib/python2.5/site-packages/hookbox-0.2.10-py2.5.egg/hookbox/channel.py", line 164, in publish
    success, options = self.server.http_request('publish', user.get_cookie(conn), form)
  File "/home/ergo/python/lib/python2.5/site-packages/hookbox-0.2.10-py2.5.egg/hookbox/server.py", line 97, in http_request
    form_body = urllib.urlencode(form)
  File "/usr/lib/python2.5/urllib.py", line 1250, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)
</pre>

**Comment by desmaj** [comment]
we should probably encode the payload as utf-8 and set the charset on the callback requests.

**Comment by mcarter** [comment]
I commited a fix. See if trunk works.

**Comment by mcarter** [comment]
Fixed in latest trunk. (confirmed by ergo in irc channel)
