### ISSUE TITLE
installation issues.

### ISSUE THREAD

**Issue by HungryJake** [play-co/hookbox#43]
Hi,

I was trying to install hookbox on my Fedora 9. Using Python 2.5.1 with setuptools. 
I've got this error below. And what are the commands to start the hookbox server? I wasn't able to find it in the documentation. 
thanks

[root@DrkServ hookbox]# hookbox 
Traceback (most recent call last): 
Traceback (most recent call last): 
  File "/usr/bin/hookbox", line 8, in <module> 
    load_entry_point('hookbox==0.3.2', 'console_scripts', 'hookbox')() 
  File "/usr/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 318, in load_entry_point 
  File "/usr/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 2221, in load_entry_point 
  File "/usr/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 1954, in load 
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.2-py2.5.egg/hookbox/start.py", line 2, in <module> 
    import output_wrapper 
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.2-py2.5.egg/hookbox/output_wrapper.py", line 46, in <module> 
    import eventlet 
  File "/usr/lib/python2.5/site-packages/eventlet-0.9.9-py2.5.egg/eventlet/**init**.py", line 45, in <module> 
    traceback.print_exc() 
  File "/usr/lib/python2.5/traceback.py", line 227, in print_exc 
    print_exception(etype, value, tb, limit, file) 
  File "/usr/lib/python2.5/traceback.py", line 124, in print_exception 
    _print(file, 'Traceback (most recent call last):') 
  File "/usr/lib/python2.5/traceback.py", line 13, in _print 
    file.write(str+terminator) 
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.2-py2.5.egg/hookbox/output_wrapper.py", line 8, in write 
    self.outputter.write(self.orig, data) 
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.2-py2.5.egg/hookbox/output_wrapper.py", line 40, in write 
    eventlet.spawn(self.do_write) 
NameError: global name 'eventlet' is not defined

**Comment by mcarter** [comment]
It looks like you need to install eventlet as well. Try: easy_install eventlet

If that doesn't work, look for a specific python/eventlet package in your package manager.

**Comment by balepc** [comment]
Try installing the following packages

sudo easy_install pyOpenSSL
sudo easy_install rtjp_eventlet
sudo easy_install greenlet
