### ISSUE TITLE
Admin traceback "ValueError: list.remove(x): x not in list"

### ISSUE THREAD

**Issue by mcarter** [play-co/hookbox#46]
Traceback (most recent call last):
  File "/home/hookbox/env/lib/python2.6/site-packages/eventlet-0.9.9-py2.6.egg/eventlet/hubs/hub.py", line 285, in fire_timers
    timer()
  File "/home/hookbox/env/lib/python2.6/site-packages/eventlet-0.9.9-py2.6.egg/eventlet/hubs/timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "/home/hookbox/env/lib/python2.6/site-packages/eventlet-0.9.9-py2.6.egg/eventlet/event.py", line 167, in _do_send
    waiter.throw(_exc)
  File "/home/hookbox/env/lib/python2.6/site-packages/eventlet-0.9.9-py2.6.egg/eventlet/greenthread.py", line 202, in main
    result = function(_args, **kwargs)
  File "/home/hookbox/src/hookbox/hookbox/admin/admin.py", line 418, in _run
    self._cleanup()
  File "/home/hookbox/src/hookbox/hookbox/admin/admin.py", line 423, in _cleanup
    self._admin_app.logout(self)
  File "/home/hookbox/src/hookbox/hookbox/admin/admin.py", line 81, in logout
    self.conns.remove(conn)
ValueError: list.remove(x): x not in list

**Comment by mcarter** [comment]
fixed in turnk
