### ISSUE TITLE
installation issues : NameError: global name 'eventlet' is not defined

### ISSUE THREAD

**Issue by Plo** [play-co/hookbox#51]
Hi,

We're trying to install Hookbox but this error appears every time : 
# 

[dev@xxx]$ hookbox -help
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/bin/hookbox", line 8, in <module>
    load_entry_point('hookbox==0.3.3', 'console_scripts', 'hookbox')()
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 277, in load_en                                  try_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 2179, in load_e                                  ntry_point
    return ep.load()
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1912, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.3-py2.5.egg/hookbox/start.p                                  y", line 2, in <module>
    import output_wrapper
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.3-py2.5.egg/hookbox/output_                                  wrapper.py", line 46, in <module>
    import eventlet
  File "/usr/lib/python2.5/site-packages/eventlet-0.9.10.dev1-py2.5.egg/eventlet                                  /**init**.py", line 45, in <module>
    traceback.print_exc()
  File "/usr/lib/python2.5/traceback.py", line 227, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/lib/python2.5/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/lib/python2.5/traceback.py", line 13, in _print
    file.write(str+terminator)
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.3-py2.5.egg/hookbox/output_                                  wrapper.py", line 8, in write
    self.outputter.write(self.orig, data)
  File "/usr/lib/python2.5/site-packages/hookbox-0.3.3-py2.5.egg/hookbox/output_                                  wrapper.py", line 40, in write
    eventlet.spawn(self.do_write)
NameError: global name 'eventlet' is not defined
# 

After reading other issues, we update eventlet to 0.9.10dev but the problem is still there.

Any ideas of something we've missed ?
All my thanks in advance :)

Plo.

**Comment by balepc** [comment]
You probably have python 2.5.

Try to migrate to 2.6. Here is instructions for ubuntu 8.04 (http://www.talino.org/tutorials/install-python-261-without-trashing-ubuntu/)

**Comment by marie-dk** [comment]
I experienced the same issue on FreeBSD with python 2.5, and upgrading to 2.6 did the trick :-)

**Comment by balepc** [comment]
You could also try installing pyOpenSSL to run it on python 2.5

sudo easy_install pyOpenSSL

**Comment by Plo** [comment]
Works fine with Python 2.7 !
Thanks for your help.
