### ISSUE TITLE
Session Timeouts and Exception: Not Connected

### ISSUE THREAD

**Issue by digipigeon** [play-co/hookbox#71]
I am experiencing the error below on the command line and sessions expiring because the connections are not been made.

I have a channel setup to poll an address and it does not appear that it is been polled correctly.

2010-09-21 14:36:49,599 - HookboxConn - WARNING - Unexpected error: Not Connected
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/hookbox-0.3.4dev-py2.6.egg/hookbox/protocol.py", line 30, in send_frame
    self._rtjp_conn.send_frame(_args, *_kw).wait()
  File "/usr/local/lib/python2.6/dist-packages/rtjp_eventlet-0.3.2-py2.6.egg/rtjp_eventlet/server.py", line 143, in send_frame
    raise Exception("Not Connected")
Exception: Not Connected

**Comment by jordoh** [comment]
I'm seeing the same thing in my logs - installing the latest rtjp_eventlet from source (http://github.com/mcarter/rtjp_eventlet) appears to reduced the frequency of the exception (though it still occurs).

I wonder if HookboxConn#send_frame should be passing if this exception occurs, in addition to passing if the exception text contains "closed".

One additional note: I don't see this exception very much until about 200+ users are connected.
