### ISSUE TITLE
hookbox "stops" listening for connections

### ISSUE THREAD

**Issue by ergo** [play-co/hookbox#86]
Hello,

it seems im also running into problem described in this thread:

http://groups.google.com/group/hookbox/browse_thread/thread/8528f6f5ffa756f2

after a while i get errors like this:

<pre>
Traceback (most recent call last):
  File "/home/points2shop/python/lib/python2.6/site-packages/eventlet/greenpool.py", line 80, in _spawn_n_impl
    func(*args, **kwargs)
  File "/home/points2shop/python/lib/python2.6/site-packages/eventlet/wsgi.py", line 510, in process_request
    proto = self.protocol(socket, address, self)
  File "/opt/python2.6/lib/python2.6/SocketServer.py", line 617, in __init__
    self.handle()
  File "/opt/python2.6/lib/python2.6/BaseHTTPServer.py", line 331, in handle
    self.handle_one_request()
  File "/home/points2shop/python/lib/python2.6/site-packages/eventlet/wsgi.py", line 195, in handle_one_request
    self.raw_requestline = self.rfile.readline(MAX_REQUEST_LINE)
  File "/opt/python2.6/lib/python2.6/socket.py", line 473, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/points2shop/python/lib/python2.6/site-packages/eventlet/greenio.py", line 217, in recv
    return fd.recv(buflen, flags)
error: [Errno 110] Connection timed out
</pre>

and i cant connect to server admin panel or as client using js - restart fixes the problem for me, but ofc isnt a long term solution.

im using Version: 0.3.4dev - or at least git revision from 2010-11-23

**Comment by skillcoder** [comment]
I have same problem.
It's hapend on 80-100+ users

**Comment by neilgupta** [comment]
Does anybody know if this problem has been fixed, perhaps in one of the many forks of this project? I can't seem to find any evidence of a fix in any of the commit histories though. I'm experiencing similar problems on v0.3.3, which I had hoped would be more stable.
